### PR TITLE
Updated Generator to fit Node v4.0 upgrade

### PR DESCRIPTION
**Pull request by davecarter**
### Included in this PR:

- Removed references to `React` and `createComponent` in **test** folder files to avoid linting warning: 
*is defined but never used*.
- Updated Initial message.

Please review @danderu @carlosvillu !

### CODE REVIEW

**Comment by carlosvillu** [comment]
About the tests, @FranDelaCasa is working in a new version of `test_utilities`

**Comment by davecarter** [comment]
Should I leave it as is then @carlosvillu ?
I've removed references in order to meet current linting. If Fran has a working progress I can get rid of this change.

**Comment by FranDelaCasa** [comment]
:+1:

**Comment by danderu** [comment]
Cool! :+1:

**Pull request merged**
