### PR TITLE
Remove jscs from linting task.

### PR DESCRIPTION
**Pull request by marcelopereirascmspain**
@carlosvillu @danderu @davecarter @nucliweb can you review it please?
2 :+1: are enough. The last one merges and deletes the branch.

Linting is not working with jscs.
We agreed to remove jscs and use only eslint instead.

```bash
> cat ./{src,test}/**/*.{js,jsx} | jscs

cat: ./src/**/*.js: No such file or directory
cat: ./test/**/*.jsx: No such file or directory

assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: Unable to add an error, `line` should be a number greater than 0 but undefined given
    at Object.Errors.add (/Users/marcelo.pereira/sui-icon/node_modules/jscs/lib/errors.js:41:9)
    at StringChecker._addParseError (/Users/marcelo.pereira/sui-icon/node_modules/jscs/lib/string-checker.js:185:16)
    at StringChecker.checkString (/Users/marcelo.pereira/sui-icon/node_modules/jscs/lib/string-checker.js:113:18)
    at Socket.<anonymous> (/Users/marcelo.pereira/sui-icon/node_modules/jscs/lib/checker.js:201:26)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
```

### CODE REVIEW

**Comment by nucliweb** [comment]
:+1:

**Comment by carlosvillu** [comment]
I am agree with remove that!
:+1:

**Comment by carlosvillu** [comment]
@marcelopereirascmspain Please remove the "dotfile" from the front-end-rules package

**Comment by danderu** [comment]
Ok, but shouldn't we migrate the removed jscs rules to the .eslintrc file? https://github.com/SUI-Components/generator-sui-react/commit/5dfce98a37fe3359d999c139b9ffb4d845b40aa9

**Comment by marcelopereirascmspain** [comment]
@danderu I think it's easier to start with a good .eslintrc template and build up on that (we already did that in a meeting), then trying to map each jscs property to eslint.

@carlosvillu the front-end-rules is another npm module?

**Comment by carlosvillu** [comment]
@marcelopereirascmspain https://github.com/scm-spain/frontend-pre-commit-rules

**Comment by davecarter** [comment]
It would be great to get rid of JSCS the sooner the better. Even if we don't have every functionality included in eslint yet. 

So far we must to manually remove JSCS every time we create a new component to be able to commit.

Cheers

**Comment by marcelopereirascmspain** [comment]
@davecarter can you merge & delete please?
The person who creates the pull request shouldn't merge it.
Thx! :)

**Comment by danderu** [comment]
Done :)

**Comment by davecarter** [comment]
I guess I'm quite late here .. :)

**Pull request merged**
